version: '3.0'
services:
  poll:
    build:
      context: "./poll"
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - poll-tier
    restart: always
    environment:
      DB_ADRESS: "./"

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - poll-tier
      - back-tier
    restart: always


  worker:
    build:
      context: "./worker"
      dockerfile: Dockerfile
    networks:
      - back-tier
    restart: always
    environment:
      DB_ADRESS: "./"

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - result-tier
      - back-tier
    environment:
      POSTGRES_PASSWORD: password

  result:
    build:
      context: "./result"
      dockerfile: Dockerfile
    ports:
      - 5001:80
    networks:
      - result-tier
    restart: always
    environment:
      DB_ADRESS: "./"

volumes:
  db-data:

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge
